# d^2 = 0 bisect diagnostic for OPEN_QUESTIONS.md item 3.
#
# The cabled 5_1 knot is known to fail the d^2 = 0 check over F_3 (but
# computes cleanly over F_2).  This script runs toReduced_BNComplex on
# the cabled tangle across both sign conventions and both fields, and
# records whether the final validate() succeeds.  When it fails, the
# mor entries responsible for the non-zero d^2 are logged so a math
# collaborator can see whether the "corrected" sign flip (applied in
# BNAlgebra.mor.ToCob's even-negative branch) fixes the issue.
#
# Usage:   python3 KhT d2_bisect
# Output:  examples/d2_bisect/d2_bisect_output.md

import io as _io
import os as _os
import numpy as _np


def _run_bisect(Tangle=Tangle, BNAlgebra=BNAlgebra,
                _io=_io, _os=_os, _np=_np):

    SIGN_CONVENTIONS = ["legacy", "corrected"]
    CABLES = [
        ("5_1",  "cup1.pos0.neg1.neg1.neg1.pos0.cap1"),
    ]
    FIELDS = [2, 3]

    def d2_failures(BN):
        # Returns a list of ((row, col), repr(mor)) for non-zero entries
        # of d^2 after mod-p simplification.  Empty list means d^2 = 0.
        squared = _np.tensordot(BN.diff, BN.diff, axes=(-2, -1))
        failures = []
        for i, row in enumerate(squared):
            for j, m in enumerate(row):
                if m == 0:
                    continue
                m.simplify_mor(BN.field)
                if m != 0:
                    failures.append(((i, j), str(m)))
        return failures

    def one_run(name, slice_str, field):
        buf = _io.StringIO()
        buf.write("### {} over F_{}\n\n".format(name, field))
        try:
            cabled = Tangle.from_legacy(slice_str, topends=1, botends=1).Cable()
            BN = cabled.toReduced_BNComplex(1000, field)
        except Exception as e:
            buf.write("  construction raised: {}\n\n".format(e))
            return buf.getvalue()

        fails = d2_failures(BN)
        if not fails:
            buf.write("  d^2 = 0 check passes ({} gens).\n\n".format(len(BN.gens)))
            return buf.getvalue()

        buf.write("  d^2 = 0 FAILS ({} gens, {} non-zero squared entries).\n"
                  .format(len(BN.gens), len(fails)))
        buf.write("  First few offending entries:\n\n")
        for (rc, rep) in fails[:5]:
            buf.write("  * {}: {}\n".format(rc, rep))
        buf.write("\n")
        return buf.getvalue()

    outdir = _os.path.join("examples", "d2_bisect")
    if not _os.path.exists(outdir):
        _os.makedirs(outdir)
    outpath = _os.path.join(outdir, "d2_bisect_output.md")
    with open(outpath, "w") as f:
        f.write("# d^2 = 0 bisect output\n\n")
        f.write("Generated by examples/d2_bisect.py for OPEN_QUESTIONS.md item 3.\n")
        f.write("Each cell runs `Tangle.from_legacy(...).Cable().toReduced_BNComplex(1000, p)`\n")
        f.write("and reports whether the resulting BN complex passes the d^2 = 0 check.\n\n")
        for conv in SIGN_CONVENTIONS:
            prev = BNAlgebra.set_sign_convention(conv)
            try:
                f.write("## Sign convention: {}\n\n".format(conv))
                for p in FIELDS:
                    f.write("### F_{}\n\n".format(p))
                    for name, slice_str in CABLES:
                        f.write(one_run(name, slice_str, p))
            finally:
                BNAlgebra.set_sign_convention(prev)
    print("wrote {}".format(outpath))


_run_bisect()
